spring:
  application:
    name: travel-blog-app


  datasource:
    url: jdbc:postgresql://localhost:5432/travel_blog_db
    username: postgres
    password: '#Halhalhal123'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # or create-drop, none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  address: 0.0.0.0
  ssl:
    enabled: true
    key-store: classpath:devcert.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: devcert

jwt:
  secret: your-secret-key-change-this-in-production-to-a-long-random-string-at-least-256-bits
  expiration: 86400000 # 24 hours in milliseconds