spring:
  application:
    name: travel-blog-app

  datasource:
    url: jdbc:postgresql://localhost:5432/travel_blog_db
    username: postgres
    password: '#Halhalhal123'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create    # or create-drop, none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
